name: sar_vegetation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - lightgbm
  - joblib
  - tqdm
  - geopandas
  - rasterio
  - shapely
  - jupyter
  - notebook
  - pyproj
  - pillow
  - numba
  - xarray
  - h5py
  - scipy
  - patsy
  - networkx
  - python-dateutil


  