name: sar_vegetation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.1
  - scikit-learn=1.3
  - matplotlib=3.8
  - seaborn=0.12
  - statsmodels=0.18
  - lightgbm=4.2
  - joblib=1.3
  - tqdm=4.67
  - geopandas=1.2
  - rasterio=1.3
  - shapely=2.1
  - jupyter=2.5
  - notebook=7.3
  - pyproj=3.6
  - pillow=10.1
  - numba=0.57
  - xarray=2025.7
  - h5py=3.9
  - scipy=1.12
  - statsmodels-base=0.18
  - patsy=0.6
  - networkx=3.2
  - python-dateutil=2.9
  - matplotlib-base=3.8

  